app_key: "dq7nlsroiuq1uhv"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "jjzjgbvhlmi2nt5a"
access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
user_id: "43175908"
access_type: "app_folder"